### PR TITLE
single flag for output; closes #166

### LINKED ISSUE #166: Merge output flags into a single `output` flag
Currently, we have `--json`, `--csv`, `--table` as options for output. We should scrap these in favor of a single `--output` flag that takes "json", "csv", and "table" as values.

### PR DESCRIPTION
**Pull request by jrperritt**

### CODE REVIEW

**Comment by kenperkins** [comment]
Works as prescribed. I think the option in the globals section should come below `--profile`.

**Comment by jrperritt** [comment]
I consolidated the global flags. Are the ordered now how you're expecting @kenperkins ?

**Comment by kenperkins** [comment]
Perfecto! :+1:

**Comment by rgbkrk** [comment]
:shipit: Looks great.

I'll miss `--json` but alas. :sob:

**Pull request merged**
