### PR TITLE
rack init

### PR DESCRIPTION
**Pull request by jrperritt**
This command (`rack init`) would try to set up command completion for linux and mac users.

### CODE REVIEW

**Comment by jrperritt** [comment]
I tested these in my Linux and Mac environments, but it'd be good if others could test as well.

**Comment by jrperritt** [comment]
Any suggestions for a better name? Currently, this is just for setting up command completion, but leaving the subcommand vague (like `init`) allows us to add more logic to it without changing the name in the future.

**Comment by kenperkins** [comment]
Works for me on OSX. First time I've enabled command completion, works like a charm.

**Comment by jrperritt** [comment]
Cool, that's great to hear; thanks for testing. Let's merge to let users who don't have a Go development environment set up test it out.

**Pull request merged**
