### PR TITLE
[wip] Empty container; closes #175

### LINKED ISSUE #175: feature request: emptying containers
related to #174, it would be really cool if I could empty all the contents of a container as a separate command like so:

```bash
rack files container empty --name foo
```

### PR DESCRIPTION
**Pull request by jrperritt**

### CODE REVIEW

**Comment by jamiehannaford** [comment]
:+1:

**Comment by jrperritt** [comment]
Do we like the `purge` flag for the `container delete` command or should we just have users do something like:
 `rack files container empty --name containerName && rack files container delete --name containerName` 
?

**Comment by kenperkins** [comment]
I think it's ok to leave it. It's a slightly higher abstraction.

**Comment by jrperritt** [comment]
ugh, I accidentally merged this into #197

**Pull request closed without merging**
