### PR TITLE
posh command completion; closes #56

### LINKED ISSUE #56: PowerShell command completion
I don't know the effort level involved in this, but it's probably worth looking into.

### PR DESCRIPTION
**Pull request by jrperritt**

### CODE REVIEW

**Comment by jrperritt** [comment]
@hdansou @DonSchenck @carolynvs Can y'all verify that [this](https://github.com/jrperritt/rack/blob/posh-command-completion/setup/commandcompletion_posh.ps1) script allows for `rack` command-completion in PowerShell? It basically overrides the `TabExpansion2` function such that non-rack commands complete as normal, and `rack` commands are completed from a list of options (commands/flags). I tested it with PowerShell_ISE v4 but, (as a non-Windows user/developer) I'd prefer verification. Also, if y'all know of a better way to do this, please feel free to make changes.

**Comment by carolynvs** [comment]
@jrperritt What do I need to do in order to test it out? I downloaded the script and ran in in a powershell session. Then tried typing `.\rack.exe ser[TAB]` to get it to complete but it isn't working.  I asssume I'm missing a setp to install it properly?

**Comment by jrperritt** [comment]
It sounds like this `ps1` script only works in PowerShell_ISE (and not regular PowerShell), but I'm not sure why. I'll leave it unmerged until we can resolve that issue.

**Comment by carolynvs** [comment]
:+1: Works great in both ISE and shell.

**Comment by jrperritt** [comment]
great, thank you for testing @carolynvs :smile:

**Comment by rgbkrk** [comment]
:shipit:

**Pull request merged**
