### PR TITLE
[wip] Block storage

### PR DESCRIPTION
**Pull request by rgbkrk**
This is a continuation of #36, looks like I'll want to rebase again making sure to set @mdarby as the author.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Here's the current state of affairs:

```
$ go build -o rack && ./rack blockstorage volumes list
ID					DisplayName	DisplayDescription	Size	VolumeType	SnapshotID	Attachments	CreatedAt
b2d946f4-5012-4188-98b6-67f76bf15dfd	<nil>		<nil>			50	SSD				[]		2015-05-23T13:25:52.000000
00e6afa6-fd6e-4eac-8e52-f0a02f43eab7	<nil>		<nil>			50	SSD				[]		2015-04-29T16:51:51.000000
8d30b958-92b2-4737-82f6-15f3f852135e	<nil>		<nil>			50	SSD				[]		2015-01-12T23:52:03.000000
6f2d2c39-f559-46db-a1f6-fa0dba12f198	<nil>		<nil>			50	SSD				[]		2015-01-12T23:51:32.000000
0017f634-8cf0-49a8-99ae-0a44764bd0a6	<nil>		<nil>			50	SSD				[]		2015-01-12T23:12:22.000000
7b85166c-963c-47a9-93c5-a9f6699f7a92	<nil>		<nil>			50	SSD				[]		2015-01-07T21:14:18.000000
7a7870e7-65f7-4f3a-91b9-75a26b9fd0d4	<nil>		<nil>			50	SSD				[]		2015-01-07T00:18:39.000000
```

Would the display name or description normally be set on volumes that were created as part of typical server creation?

**Comment by jrperritt** [comment]
You mean typical volume creation? I think the display name and display description are optional values for creating a volume.

**Comment by rgbkrk** [comment]
I'm assuming I just need `nil -> ""` then.

**Comment by jrperritt** [comment]
Yeah, should be.

**Comment by rgbkrk** [comment]
How bout them apples?

```
$ go build -o rack && ./rack blockstorage volumes list
ID					Name							Description	Size	Volume Type	Snapshot ID	Attachments	Created
b2d946f4-5012-4188-98b6-67f76bf15dfd	System disk for 157a87c4-c746-4efb-9bce-55940f720705			50	SSD				[]		2015-05-23T13:25:52.000000
00e6afa6-fd6e-4eac-8e52-f0a02f43eab7	System disk for 637b6370-d0a2-47d5-b744-5b782b0e1e0d			50	SSD				[]		2015-04-29T16:51:51.000000
8d30b958-92b2-4737-82f6-15f3f852135e	System disk for 43d768da-1304-40c9-a741-2afcd52853e9			50	SSD				[]		2015-01-12T23:52:03.000000
6f2d2c39-f559-46db-a1f6-fa0dba12f198	System disk for 6c592c8d-24cd-4d82-8eb9-e51025903803			50	SSD				[]		2015-01-12T23:51:32.000000
0017f634-8cf0-49a8-99ae-0a44764bd0a6	System disk for b4d78a2e-af00-481b-a677-11e8e1764c00			50	SSD				[]		2015-01-12T23:12:22.000000
7b85166c-963c-47a9-93c5-a9f6699f7a92	System disk for ba87aa6e-91a2-4d5d-9e2f-59d53540c9b1			50	SSD				[]		2015-01-07T21:14:18.000000
7a7870e7-65f7-4f3a-91b9-75a26b9fd0d4	System disk for cb49fd97-9049-49ce-bf21-89634340b672			50	SSD				[]		2015-01-07T00:18:39.000000
$ go build -o rack && ./rack blockstorage snapshots list
ID	Name	Description	Metadata	Size	Status	Volume ID
```

**Comment by rgbkrk** [comment]
Our tables never show up well in copy pasta.

**Comment by jrperritt** [comment]
closing in favor of #124 . these commits are included there.

**Pull request closed without merging**
